backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "cv"
    label: "My CV"
    files:
      - label: "Main CV Content"
        name: "main"
        file: "cms-data/cv.md"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Skills", name: "skills", widget: "list" }
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Project Name", name: "project_name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
